import type { Metadata } from "next";
import "./globals.css";
import "./app.css";
import { mr_med, lxe } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mr_med.variable} ${lxe.className}  ${lxe.variable} `}>
        {children}
      </body>
    </html>
  );
}
